name: CI

on:
  push:
    branches: [master]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Build wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy-wheel:
    runs-on: ubuntu-latest
    needs: build-wheel
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Deploy wheel
        env:
          DATABRICKS_DOMAIN: ${{ secrets.DATABRICKS_DOMAIN }}
          DATABRICKS_API_TOKEN: ${{ secrets.DATABRICKS_API_TOKEN }}
          DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
        run: |
          export PYTHONPATH=".:$PYTHONPATH"
          python tools/deploy_wheel.py
